### ISSUE TITLE
[UI Test Reporting]: "Details can be found under each [variant#]." test result is useless and confusing

### ISSUE THREAD

**Issue by joshgoebel** [exercism/python-test-runner#102]
Honestly I actually thought the test runner was simply glitching.  I thought perhaps the variants would be listed _right there_.  I never even glanced at the second test failure because I was trying to resolve the first failure.  These "i have no details, nothing useful to learn here" test failures should be scrubbed from the test runner results and only the failing variants should remain.  Thankfully this is easy to do with jq:

```
cat test.json | jq 'del(.tests[] | select(.message | contains("[variant#]")))'
```

Removes all test results with `[variant#]` in the message string.  I tested this with JSON from the actual Python test runner...

There are perhaps other ways to solve, but Bethany mentioned this may be hard to do at the Python level for a few reasons.

---

This makes the startup experience with the Python track pretty frustrating for anyone who doesn't keep reading past the first failing test.  I'd imagine others are surely hitting this and just not reporting it.

**Comment by joshgoebel** [comment]
Ok, actually that breaks if `message` is missing (in the case of success), we want to be able to say:

- delete IF has .message AND .message contains "[variant#]"

...but that still should be workable with JQ, just I don't know the syntax off the top of my head.  

Bethany pointed out there may be other ways to deal with the usability issue here.  This was just the first thing I thought of since to me the first failure has zero useful data - because everything you see is 100% repeated in the second failure - and in my case I didn't even look past the first failure since I thought the system was just broken... I haven't seen this type of "aggregate" test runner reporting in any of the other tracks where I'm a mentor or student.  

I do see the usefulness of this (in the success cases), just think the failure case could use a little more TLC. :)

**Comment by BethanyG** [comment]
The other issue here is that it is the main test that carries the task association.  So removing it removes the task grouping.

**Comment by joshgoebel** [comment]
I'm continuing on the Python track now and another issue here is that the Exercism UI hides/collapses all failing tests other than the first, which exacerbates this issue - since it encourages you NOT to look at the second test... I find I'm now having to:

- run tests
- minimize the first (not helpful) test result
- open the second (helpful) test result

**Comment by joshgoebel** [comment]
> The other issue here is that it is the main test that carries the task association. 

I'm not sure I follow, all I see in the JSON is `task_id` which all the  test results share (for a given task)...
