### ISSUE TITLE
Get test and source filenames from exercise config.json

### ISSUE THREAD

**Issue by cmccandless** [exercism/python-test-runner#49]
See thread https://github.com/exercism/v3/pull/2584#discussion_r515492123

**Comment by cmccandless** [comment]
@ErikSchierboom do you know how other test runners are handling multiple test files in their results.json? Presumably, there is still just one results.json, and it is the merged results of all test files.

**Comment by cmccandless** [comment]
Ah, nevermind. I just figured out how to have `pytest` handle this for me.

**Comment by ErikSchierboom** [comment]
Great! It should indeed be merged into a single file.
